# Generated by Django 4.2.17 on 2025-01-10 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sales_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
