# Generated by Django 4.2.17 on 2025-01-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_created_at_sales_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='commission',
        ),
    ]
