# Generated by Django 4.2.17 on 2025-01-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_sales_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='commission',
        ),
    ]
