# Generated by Django 4.2.17 on 2025-01-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_sales_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='佣金'),
        ),
    ]
