# Generated by Django 4.2.17 on 2025-01-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sales_commission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
